apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-personhendelse
    team: teamdigihot
  name: hm-personhendelse
  namespace: teamdigihot
spec:
  image: "{{image}}"
  strategy:
    type: Recreate
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  env:
  {{#each this}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
